prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/av_css.sql
@@application/shared_components/files/av_min_css.sql
@@application/shared_components/files/av_js.sql
@@application/shared_components/files/av_min_js.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/apex_nitro.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/applications.sql
@@application/shared_components/user_interface/lovs/components_chart.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/pages.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/apex.sql
@@application/shared_components/security/authentications/no_authentication.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00010.sql
@@application/pages/page_00020.sql
@@application/pages/page_00030.sql
@@application/pages/page_00040.sql
@@application/pages/page_00050.sql
@@application/pages/page_00060.sql
@@application/pages/page_00100.sql
@@application/pages/page_00200.sql
@@application/pages/page_00300.sql
@@application/pages/page_00400.sql
@@application/pages/page_00500.sql
@@application/pages/page_00510.sql
@@application/pages/page_00600.sql
@@application/pages/page_00700.sql
@@application/pages/page_00701.sql
@@application/pages/page_00702.sql
@@application/pages/page_00703.sql
@@application/pages/page_00704.sql
@@application/pages/page_00705.sql
@@application/pages/page_00706.sql
@@application/pages/page_00707.sql
@@application/pages/page_00708.sql
@@application/pages/page_00709.sql
@@application/pages/page_00710.sql
@@application/pages/page_00715.sql
@@application/pages/page_00720.sql
@@application/pages/page_00730.sql
@@application/pages/page_00740.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_av_general_pkg.sql
@@application/deployment/install/install_av_applications_v.sql
@@application/deployment/install/install_av_components_v.sql
@@application/deployment/install/install_av_css_v.sql
@@application/deployment/install/install_av_javascript_v.sql
@@application/deployment/install/install_av_pages_v.sql
@@application/deployment/install/install_av_plsql_v.sql
@@application/deployment/install/install_av_visibility_v.sql
@@application/deployment/install/install_av_visibility_overview_v.sql
@@application/deployment/install/install_av_p0100_js_code_by_page_v.sql
@@application/deployment/install/install_av_p0200_css_code_by_page_v.sql
@@application/deployment/install/install_av_p0300_plsql_code_by_page_v.sql
@@application/deployment/install/install_av_page_links_v.sql
@@application/deployment/install/install_av_plugins_v.sql
@@application/deployment/install/install_av_p0600_not_used_auth_schemes_v.sql
@@application/deployment/install/install_av_p0708_legacy_subst_strings_v.sql
@@application/deployment/install/install_av_page_complexity_v.sql
@@application/deployment/install/install_av_p0600_tabs_v.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
